replicaCount: 1

image:
  repository: ghcr.io/mullerhub/minha-app-python
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: minha-app.local

appColor: "blue"
